# This file contains values from Cookiecutter

default_context:
  project_name: "rhubarb"
  project_description: "Rhubarb is a library that simplifies realtime streaming for a number of backends into a single API"
  organization: "mopeyjellyfish"
  license: "MIT"
  minimal_python_version: 3.9
  github_name: "mopeyjellyfish"
  email: "dev@davidhall.tech"
  version: "0.1.0"
  line_length: "88"
  create_example_template: "none"
