name: Publish to PyPI
on:
  release:
    types:
      - published

jobs:
  pypi_release:
    name: Builds Using Poetry and Publishes to PyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
      - name: Install poetry
        run: make poetry-download
      - run: poetry install
      - run: poetry config pypi-token.pypi "${{ secrets.PYPI_TOKEN }}"
      - name: Publish package
        run: poetry publish --build
